name: Push Data to GitHub

on:
  repository_dispatch:
    types: [trigger-push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v2

    - name: Pythonスクリプトを実行してデータをテキストファイルに保存
      run: |
        echo "${{ github.event.client_payload.data }}" > input_data.txt
        python save_data.py

    - name: テキストファイルをコミットしてプッシュ
      run: |
        git add data.txt
        git commit -m "Add data from GitHub Pages input"
        git push
